language: node_js
node_js: 13

stages:
  - testing
  - deployement

jobs:
  include:
    - stage: testing
      name: compile
      install: npm install
      script: npm run build

    - stage: testing
      name: linter
      install: npm install
      script: skip #linter
